### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Astroschlumpf** [WoWs-Builder-Team/WoWs-ShipBuilder#14]
**Describe the bug**
Setup.exe does not support path selection for destination folder.

**To Reproduce**
1. Execute Setup.exe.

**Expected behavior**
Setup has an option to change the folder.

**Additional context**
The option to change the program path can be crucial on some systems due to individual specifications.

**Comment by yesod30** [comment]
This is a limitation of the library we use to create and distribuite update [Clows.Squirrel](https://github.com/clowd/Clowd.Squirrel). Nothing we can do on our end, since it's auto generated. All the app file get put in the localAppData folder, that is the folder indicated by Microsoft itself that should be used to store application data. This is also due to write and read permission being available for all application in those folder.

Closing this since it's intended and an external library issue in the first place.

**Comment by Astroschlumpf** [comment]
Oof, that's bad Microsoft hocus-pocus. Too bad this has its roots so deep in the OS developer mindset
