### ISSUE TITLE
[Bug] Virus in Windows Setup file

### ISSUE THREAD

**Issue by igorzeler** [WoWs-Builder-Team/WoWs-ShipBuilder#200]
**Describe the bug**
Trojan Ransom:Win32/Spursint.F!cl reported in Windows Setup file by Windows Defender.

**To Reproduce**
1. Go to downloaded file
2. Run antivirus scanner
3. See error

**Expected behavior**
No action

**Screenshots**

**Program version. You can find it in the Info tab of the setting window**
1.62

**Data version. You can find it in the Info tab of the setting window**
16 Feb 2023
![virus](https://user-images.githubusercontent.com/12586337/220279353-2270ac55-0ef0-45f4-a76e-adf8f90e692c.png)

**Additional context**

**Comment by iTTou** [comment]
Hello and ty for the report. If you downloaded the program from our github repo (https://github.com/WoWs-Builder-Team/WoWs-ShipBuilder/releases/tag/v1.6.2) then that's 100% a false positive due to the application not being signed. Signing an application is very expensive and beyond our possibilites atm. Because of that AV programs sometimes flags it as virus. If you didnt download it from our repo then i strongly advise you to remove it since we cannot guarantee the safeness of our application if not downloaded from our official git repo. If you still do not trust the application you can use the web version at https://app.wowssb.com/

**Comment by floribe2000** [comment]
This is a false positive, for details see https://forum.worldofwarships.eu/topic/156510-121toolendehuitjpbrru-wows-shipbuilder-v162/?tab=comments#comment-4355024 and https://www.virustotal.com/gui/file/5e362bda170fc7a54ee510c9b9d3066e1f13533989f2465d0c8a71d96b598861/
